
[common_server]
	#Weight of silver ore spawning
	#Range: 0 ~ 256
	silverOreWeight = 30
	#Only considered if terrablender installed. Heigher values increase Werewolf region weight (likelyhood to appear)
	#Range: 1 ~ 1000
	werewolfBiomeWeightTerrablender = 2
	#Disable werewolf forest generation
	disableWerewolfForest = false

